# Generated by Django 3.2.2 on 2021-05-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(max_length=20)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('contract_no', models.IntegerField(max_length=120)),
                ('email_id', models.CharField(max_length=250)),
                ('team_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Document_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_type', models.CharField(max_length=20)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.users')),
            ],
        ),
    ]
